# Generated by Django 6.0.3 on 2026-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ait', models.CharField(db_index=True, max_length=50, unique=True)),
                ('placa', models.CharField(db_index=True, max_length=20)),
                ('valor_infracao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_infracao', models.DateField(db_index=True)),
                ('data_na', models.DateField(blank=True, null=True)),
                ('data_np', models.DateField(blank=True, null=True)),
                ('codigo', models.CharField(db_index=True, max_length=20)),
            ],
        ),
    ]
