# Generated by Django 6.0.3 on 2026-04-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_arquivoimportado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código da infração, sem hífens ou pontos. Ex: 74550', max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='infracao',
            name='codigo',
        ),
        migrations.AddField(
            model_name='infracao',
            name='enquadramento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infracoes', to='dashboard.enquadramento'),
        ),
    ]
