# Generated by Django 6.0.3 on 2026-04-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_enquadramento_remove_infracao_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquadramento',
            options={'ordering': ['codigo', '-data_inicio']},
        ),
        migrations.AddField(
            model_name='enquadramento',
            name='competencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enquadramento',
            name='data_final',
            field=models.DateField(blank=True, help_text="Data final da validade deste enquadramento. Nulo significa 'em vigor'.", null=True),
        ),
        migrations.AddField(
            model_name='enquadramento',
            name='data_inicio',
            field=models.DateField(db_index=True, default='1900-01-01', help_text='Data de início da validade deste enquadramento.'),
        ),
        migrations.AddField(
            model_name='enquadramento',
            name='infrator',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='enquadramento',
            name='pontos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquadramento',
            name='portaria',
            field=models.CharField(blank=True, help_text='Portaria que instituiu o enquadramento.', max_length=30),
        ),
        migrations.AddField(
            model_name='enquadramento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquadramento',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Código da infração, sem hífens ou pontos. Ex: 74550', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='enquadramento',
            constraint=models.UniqueConstraint(fields=('codigo', 'data_inicio'), name='unique_codigo_data_inicio'),
        ),
    ]
