# Generated by Django 6.0.3 on 2026-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_enquadramento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquadramento',
            name='data_inicio',
            field=models.DateField(db_index=True, help_text='Data de início da validade deste enquadramento.'),
        ),
    ]
