# Generated by Django 6.0.3 on 2026-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_enquadramento_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracao',
            name='enquadramento',
        ),
        migrations.AddField(
            model_name='infracao',
            name='codigo',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
